# Basics of Python

=========================================================================================================================

**Data Types in Python:**

The purpose of data types in any programming language is that to store the inputs / literals in main memory of computer by allocating sufficient amount of memory space.

In Python Programming, we have 14 data types, which are classsified into 6 catageries

they are,

I) Fundamental Catagery Data Types 

         1) int
         2) float
         3) bool
         4) complex
         
II) Sequential Catagery Data Types

         5) str   
		 6) bytes 
		 7) bytearray
	     8) range
          
III) List Catagery Data Types (Collections Data Types)

         9) list   
		10) tuple
           
IV) Set Catagery Data Types (Collections Data Types)

        11) set   
		12) frozenset

V) Dict Catagery Data Types (Collections Data Types)

        13)dict
           
VI) None Catagery Data Types

        14) None
        
        
        
        
**1)int:**

-'int' is one of the pre-defined class  and it is treated as fundamental data type

-The purpose of 'int' data type is that to store Integer Data (Or) Integral Values (or) whole       numbers ( Values without decimal places )

**Examples:**

In [1]:
a=123
print(a,type(a))
b=100
print(b,type(b))
c=1
print(c,type(c))

123 <class 'int'>
100 <class 'int'>
1 <class 'int'>


with 'int' data type, we can also store Binary , Octal and Hexa Decimal data also.

In [3]:
a=0b1010  #binary data
print(a,type(a))
b=0o123  #octal data
print(b,type(b))
c=0xAB  #hexadecimal data
print(c,type(c))

10 <class 'int'>
83 <class 'int'>
171 <class 'int'>


**2)float**

-'float' is one of pre-defined class and treated as Fundamental data Type.

-The purpose of float data type is that "To Store Real Constant Values (or) Floating Point Values (Number with Decimal values.

**Examples:**

In [4]:
a=77.99
print(a,type(a))
b=69.9
print(b,type(b))
c=1.1
print(c,type(c))

77.99 <class 'float'>
69.9 <class 'float'>
1.1 <class 'float'>


float data allows us to store Decimal Number System values and this data type never supports Binary, Octal and Hexa Decimal Number System Values.

In [5]:
d=0b1010.0b1010 #you think this will print 10.10 but it will give error ,cause float datatype never support Binary, octal,
print(d)              #Hexadecimal no

SyntaxError: invalid syntax (<ipython-input-5-ac0ad3413110>, line 1)

-float data type allows us store the floating point values in the form of Scientific Notation

In [6]:
Sn=4.4e5   #here Sn i took for Scientific notation
print(Sn)

440000.0


**3)bool**
			
-'bool' is one of the pre-defined class and treated as Fundamental data type

-The purpose of bool data type is that " To Store True and False values (Logical values)"

**Examples:**

In [7]:
a=True
print(a,type(a))
b=False
print(b,type(b))

True <class 'bool'>
False <class 'bool'>


In [8]:
a=true
print(a)  #always use capital 'T' in True and capital 'F' in False


NameError: name 'true' is not defined

Internally, The value of True is 1 and the value of False is 0.

**Examples:**

In [9]:
a=True
b=False
c=a+b
d=a*b
e=True+True
print(c)
print(d)
print(e)

1
0
2


**4)complex**

-'complex' is one of the pre-defined class and treated as Fundamental data type

-The purpose of complex data type is that "To Store Complex Values "

-The General Format of Complex Values is  given bellow

			a+bj  (or)  a-bj 
            
	Here, 
            'a' is called Real Part
            
	        'b' is called Imaginary Part
            
		     'j' represents  sqrt(-1)
             
-here the values of Real and Imaginary parts can be int and float type

-Internally The Real part and Imiginary Parts are treated as float type

**Examples:**

In [11]:
a=2+3j
b=2-5j
c=-4-6j
d=4.1-4j
e=2.3-3.6j
print(a,type(a))
print(b,type(b))
print(c,type(c))
print(d,type(d))
print(e,type(e))

(2+3j) <class 'complex'>
(2-5j) <class 'complex'>
(-4-6j) <class 'complex'>
(4.1-4j) <class 'complex'>
(2.3-3.6j) <class 'complex'>


**5)str**

-'str' is one of the pre-defined class and it is treated as Sequence data type.

-The purpose of str data type is that " To store String data ".

-Python programming does not contains char data type and character values also stored by using str data type.

In [13]:
a='Aniket'
b="Python"
print(a,type(a))
print(b,type(b))

Aniket <class 'str'>
Python <class 'str'>


In [14]:
c='Tadaaaaaa"
print(c,type(c))

SyntaxError: EOL while scanning string literal (<ipython-input-14-41453efbea2c>, line 1)

So the thing with string datatype is when you start with single inverted comma (') then you have to end with it.
if you combine both single and dobule inverted commas(' ") then PVM will give EOL error

**6)bytes**

-'bytes' is on the pre-defined class and treated as Sequential Data Type.

-The purpose of bytes data type is that "To  store Positive Numerical Integer Values ranges from (0,256), ie. It stores from 0 to 255 only.

-bytes data types does not containing Symbolic Notation for representing bytes values but we can convert other type of values into bytes value by using  bytes()

**Examples:**

In [17]:
lst=[-1,34,0,256,69]
print(lst,type(lst)) #for now don't worry about list 
b=bytes(lst)
print(b,type(b))

[-1, 34, 0, 256, 69] <class 'list'>


ValueError: bytes must be in range(0, 256)

So in list we use no like -1 ,34 0,256, and 69. other no are okay but we used -1 and 256. but bytes only support or only stores 
no from 0-256, excluding 256

In [18]:
lst=[1,23,69,255,99]
print(lst,type(lst))
c=bytes(lst)
print(c,type(c))

[1, 23, 69, 255, 99] <class 'list'>
b'\x01\x17E\xffc' <class 'bytes'>


it will show your values in incripted format to retrive those values we gonna use loop,don't worry about loop for now, i'll explain those later

so to retrive our values,

In [21]:
for i in b[:6]:
    print(i)

1
23
69
255
99


In [22]:
#all in one cell
lst=[2,45,88,9,255]
print(lst,type(lst))
d=bytes(lst)
print(d,type(d))
for i in d[:6]:
    print(i)

[2, 45, 88, 9, 255] <class 'list'>
b'\x02-X\t\xff' <class 'bytes'>
2
45
88
9
255


**7)bytearray**

-The functionality of bytearray is exactly similar to bytes data types but bytearray data type belongs to mutable where as bytes data type belongs to immutable.

-mutable and immutable i'll explain in another video

**Examples:**

In [24]:
lst1=[23,46,255,88,90]
b=bytearray(lst1)
print(b,type(b))
for i in b[:5]:
    print(i)

bytearray(b'\x17.\xffXZ') <class 'bytearray'>
23
46
255
88
90


**8)range**

-'range' is one of the pre-defined class and is treated as sequence data type.

-The purpose of range data type is that " To store Sequence of Numerical Integer values with equal Interval Value "

Syntax 1:-

              variable_name = range(value)

**Examples:**


In [26]:
a=range(10)
print(a,type(a))
for i in range(10):
    print(i)

range(0, 10) <class 'range'>
0
1
2
3
4
5
6
7
8
9


So range dosen't include last no, for example you want range of 0-9 you add value =10 cause it will work as value-1



Syntax 2:-

          variable_name=range(start,stop)
          
**Examples:**

In [28]:
b=range(2,11)
print(b,type(b))
for i in b:
    print(i)

range(2, 11) <class 'range'>
2
3
4
5
6
7
8
9
10


Syntax 3:-  

          variable_name=range(start,stop,step)
          
**Examples:**

In [29]:
c=range(1,11,2)
print(c,type(c))
for i in c:
    print(i)

range(1, 11, 2) <class 'range'>
1
3
5
7
9


these are all the syntaxes for range, use accordingly

**9)list**

-'list' is one of the pre-defined class and treated as List type data type ( Collections data types )

=The purpose of list type data type is that " To store multiple values either of same or different type or both the data types with Unique and duplicate values "

-The elements of list must be organized in the form of square brackets [ ] and elements must separated by comma.

Syntax:             
           
           variable_name=[val1,val2....val-n]
           
**Examples:**

In [30]:
lst=[1,2,3,55,7788,98]
print(lst,type(lst))

[1, 2, 3, 55, 7788, 98] <class 'list'>


In [32]:
lst1=[12,-12,69.69,-34.66,"WoW",True,2+3j]
print(lst1,type(lst1))
len(lst1)         #we use len() to find the length 

[12, -12, 69.69, -34.66, 'WoW', True, (2+3j)] <class 'list'>


7

**Creating Empty list:**

Syntax 1:

            variable_name = list()
            
    
    
Syntax 2:
         
           variable_name = []
           
 
**Examples:**
       
       

In [33]:
lst1=list()
print(lst1,type(lst1))
lst2=[]
print(lst2,type(lst2))

[] <class 'list'>
[] <class 'list'>


**10)tuple**

-'tuple' is one of the pre-defined class and treated as List type data type(Collections data types)

-The purpose of tuple type data type is that " To store multiple values either of same or different type or both the data types with Unique and duplicate values "

-The elements of tuple must be organized in the form of braces ( ) and elements must separated by comma.

-Syntax:             

                  variable_name=( val1,val2....val-n )
                  
                  
**Examples:**

In [34]:
tpl=(1,2,55,6,78)
print(tpl,type(tpl))
tpl2=(1,23.44,-2,-33.55,'taa',False,2+4j)
print(tpl2,type(tpl2))

(1, 2, 55, 6, 78) <class 'tuple'>
(1, 23.44, -2, -33.55, 'taa', False, (2+4j)) <class 'tuple'>


**Creating Empty tuple:**

Syntax 1: 

           variable_name=tuple()
           
Syntax 2: 

           variable_name=()
           
**Examples:**
          

In [35]:
tpl=tuple()
print(tpl,type(tpl))
tpl2=()
print(tpl2,type(tpl2))

() <class 'tuple'>
() <class 'tuple'>


**Converting list into tuple  and vice versa:**

In [36]:
lst=[1,2,3,4,5,6]
print(lst,type(lst))
#converting list into tuple
t=tuple(lst)
print(t,type(t))

[1, 2, 3, 4, 5, 6] <class 'list'>
(1, 2, 3, 4, 5, 6) <class 'tuple'>


In [37]:
tpl=(3,4,5,6,7,8,9)
print(tpl,type(tpl))
#converting tuple into list
l=list(tpl)
print(l,type(l))

(3, 4, 5, 6, 7, 8, 9) <class 'tuple'>
[3, 4, 5, 6, 7, 8, 9] <class 'list'>


**11)set**

-set' is one of the pre-defined class and treated as set data type

-The purpose of set data type is that "To store multiple values either of same or different type  or both the data types with Unique Values "

-The elements of set must be organized within curly braces and elements must be separated by comma.

-An object of set never maintains insertion order

**Example:**

In [38]:
S1={1,22,55,33,22,69}
print(S1,type(S1))

{1, 33, 69, 22, 55} <class 'set'>


Here,PVM eliminated the duplicate element i.e 22, in set we can store only Unique values

**Creating Empty set:**

so creating empty set,

people may think we use {} for set, so to create empty set we will use like this 

s1={}  or s1=set{} 

lets see

In [39]:
S1={} 
print(S1,type(S1))

{} <class 'dict'>


No, its not set its dict type object 

so to create empty se we use 

Syntax:
   
           variable_name=set()
           
           
 **Examples:** 

In [40]:
S1=set()
print(S1,type(S1))

set() <class 'set'>


**Conveting list,tuple into set:**

In [41]:
lst=[2,44,5,77,889]
tpl=(222,34,666,88)
print(lst,type(lst))
print(tpl,type(tpl))
#convrting
S1=set(lst)
S2=set(tpl)
print(S1,type(S1))
print(S2,type(S2))

[2, 44, 5, 77, 889] <class 'list'>
(222, 34, 666, 88) <class 'tuple'>
{2, 5, 44, 77, 889} <class 'set'>
{88, 34, 222, 666} <class 'set'>


**12)frozenset**

Note:- The Functionality of frozenset is exactly similar to the functionality of Set but an object of frozenset belongs to Immutable and an object of set belongs to both Immutable (In the case item assignment) and Mutable (in the case add() )

**Examples:**

In [42]:
lst=[77,55,67,777]
print(lst,type(lst))
f=frozenset(lst)
print(f,type(f))

[77, 55, 67, 777] <class 'list'>
frozenset({777, 67, 77, 55}) <class 'frozenset'>


**13)dict**

-In dict data type , we have only one data type called "dict"

-"dict" is one of the pre-defined class and treated as dict data type.

-The purpose of dict data type is that "To store the (Key,Value) "

-In (Key,Value), The values of Key are Unique and values of Value may or may not be unique.

-The (Key,Value) data (or) the elements of dict must be organized in the form of curly braces { } and separated by comma

**Examples:**

In [43]:
D1={10:"Red",20:"Yellow",30:"pink"}
print(D1,type(D1))

{10: 'Red', 20: 'Yellow', 30: 'pink'} <class 'dict'>


In [44]:
D2={1:"Python",1:"java",2:"C"}
print(D2,type(D2))       #key values must be unique

{1: 'java', 2: 'C'} <class 'dict'>


In [45]:
D3={1:"python",2:"python",3:"java"}
print(D3,type(D3))          # values of value may or may not be unique

{1: 'python', 2: 'python', 3: 'java'} <class 'dict'>


In [46]:
D4={"Python":12,"Java":33,"C":35}
print(D4,type(D4))

{'Python': 12, 'Java': 33, 'C': 35} <class 'dict'>


**Creating dict :**

Syntax:

        dictobj[key1]=val1
        dictobj[key2]=val2
        .
        .
        .
        dictobj[key n]=val n
        
**Example:**

In [47]:
D1={}
#first we take key values 
D1[10]="Red"
D1[20]="Yellow"
D1[30]="Pink"
print(D1,type(D1))

{10: 'Red', 20: 'Yellow', 30: 'Pink'} <class 'dict'>


**NoneType Datatype**


-'NoneType' is one of the pre-defined  class and treated  NoneType   data type

-The values of NoneType   data type is None

-If we assign the None value to the object then that object memory space collected by Garbage Collector

-The value None is not False, space , zero 


**Examples:**

In [48]:
a=None
print(a,type(a))

None <class 'NoneType'>


In [50]:
a={10:"red",20:"yellow",30:"pinK"}
print(a,type(a))
Ex=a.get(10)
print(Ex,type(Ex))
print("*"*50)
Ex2=a.get("red")
print(Ex2,type(Ex2))

{10: 'red', 20: 'yellow', 30: 'pinK'} <class 'dict'>
red <class 'str'>
**************************************************
None <class 'NoneType'>


In next video i'll cover basic operations in python


**-------- T H A N K  Y O U -----------**